import os
import time
import psutil
import urllib2
import smtplib
import schedule
from sys import*
from email import encoders
from email.mine.text import MIMEText
from email.mine.base import MIMEBase
from email.mime.multipart import MIMEMultipart


def is_connected():
    try:
        urllib2.urlopen("https://mail.google.com/mail/u/0/#inbox",timeout=1)
        return True
    except urllib2.URLError as err:
        return false

def Mailsender(filename,time):
    try:
        fromaddr="akshaygolait95@gmail.com"
        toaddr= "akshaygolait95@outlook.com"

        msg=MIMEMultipart()

        msg['from']=fromaddr

        msg['to']=toaddr

        body="""
        hello % s,
        welcome to akshraj electricals& engineers.
        please find attached document which contains log of running process.
        log file is created at :% s

        this is autogenerated mail.

        thanks & regards,

        akshay golait
        akshay electricals
          """% (toaddr,time)


        subject="""
        akshraj electrical process log generated at :% s
        """% (time)

        msg['subject']=subject
        msg.attach(MIMEText(body,'plain'))

        attachment = open (filename,"rb")

        p=MIMEBase('application','octet-stream')

        p.set_playload((attachment).read())
        encoders.encode_base64(P)
        p.add_header('content-disposition',"attachment; filename=% s" % filename)

        msg.attach(p)

        s= smtplib. SMTP('smtp.gmail.com',587)

        s.starttis()

        s.login(fromaddr,"_______")


        text = msg.as_string()

        s.sendmail(fromaddr,toaddr,text)

        s.quit()

        print("log file successfully sent through mail")


    except exception as E:
        print("unable to sent mail.",E)

def processlog(log_dir ='akshay'):
    listprocess =[]

    if not os.path.exists(log_dir):
        try:
            os.mkdir(log_dir)
        except:
            pass

    separator =" -"*80
    log_path =os.path.join(log_dir,"akshraj electrcal log%s.log"%(time.time()))
    f = open(log_path,'w')

    f.write(separator+ "\n")
    f.write("akshraj electrical process logger:"+time.time()+"\n")
    f.write(separator +"/n")
    f.write("\n")

    for proc in psutil.process_iter():
        try:
            pinfo = proc.as_dict(attrs=['pid','name','username'])
            vrms= proc.memory_info()>vms/(1024*1024)
            pinfo['vms']=vms
            listprocess.append(pinfo);
        except (psutil.nosuchprocess,psutil.accessDenied,psutil.zombieprocess):
            pass

    for element in listprocess:
        f.write("%s\n"% element)


    print("log file is successfully generated at location %s",(log_path))

    connected= is_connected()

    if connected:
        startTime=time.time()
        mailsender(log_path,time.time())
        endTime=time.time()

        print('Took % s second to sent mail' % (endTime-startTime))
    else:
        print("There is no internet connection")

def main():
    print("____akshraj electricals & engineers_____")

    print("application name: "+argv[0])

    if (len(argv)!=2):
        print("Error : invalid number of arguments")
        exit()

    if (argv[1]== "-h")or (argv[1]=="_H"):
        print("this script is used log record of running processess")
        exit()

    if(argv[1]=="-u")or(argv[1]=="_u"):
        print("usage: Application Name Absolutepath_of_directory")
        exit()


    try:
        schedule.every(int(argv[1])).minutes.do(processlog)
        while True:
            schedule.run_pending()
            time.sleep(1)

    except valueError:
        print("error : invalid datatype of input")


    except Exception as E:
        print("Error : Invalid input",E)


if __name__=="__main__":
    main()
                            
                   
